name: Slither Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Declare default permissions as read only.
permissions: read-all

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    env:
      RSK_MAINNET_RPC_URL: ${{ secrets.RSK_MAINNET_RPC_URL }}
      RSK_TESTNET_RPC_URL: ${{ secrets.RSK_TESTNET_RPC_URL }}
      WALLET_PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}  
    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

    - name: Run Slither
      uses: crytic/slither-action@f197989dea5b53e986d0f88c60a034ddd77ec9a8 #v0.4.0
      id: slither
      with:
        node-version: 18
        sarif: results.sarif
        fail-on: none

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@b56ba49b26e50535fa1e7f7db0f4f7b4bf65d80d #v3.28.10
      with:
        sarif_file: ${{ steps.slither.outputs.sarif }}